### ISSUE TITLE
Retrieving Shipment State throws Exception with error 500

### ISSUE THREAD

**Issue by BBrunekreeft** [Trunkrs/Trunkrs-SDK-PHP#14]
When I try to retrieve a shipment state, a Trunkrs\SDK\Exception\GeneralApiException is thrown with the message `'The Trunkrs API responded with an unexpected answer of: 500'`

```
<?php 
    \Trunkrs\SDK\Settings::setCredentials(
        'myClientID',
        'myClientSecret'
    );
    \Trunkrs\SDK\Settings::useStaging();

    var_dump(\Trunkrs\SDK\Shipment::find(8414));             // This works fine
    var_dump(\Trunkrs\SDK\ShipmentState::forShipment(8414)); // Exception is thrown
?>
```

**Comment by fean** [comment]
Hey again @BBrunekreeft!

Thanks for reporting this issue! 👍 
Our back-end team will investigate this issue as soon as possible.

We will keep you updated on the progress in this thread. 🙂

**Comment by fean** [comment]
The issue has been fixed on both staging and production. 🙂
