### ISSUE TITLE
UnprocessableEntityError when trying to create shipment

### ISSUE THREAD

**Issue by JSRM99** [Trunkrs/Trunkrs-SDK-PHP#25]
**Trunkrs SDK version(s) affected**: 2.0.0
**PHP version(s) affected**: 7.3.11
**Description**  
When trying to create a shipment using the new V2 sdk, we encounter an UnprocessableEntityError (kind: "DecoderError").
The feedback provided by the server: "expected a string, got null" at "input.parcels[0].goods".

**How to reproduce**  
The code used: (Settings are set to staging environment)
```php
$details = new ShipmentDetails();

foreach ($data['collo'] as $weight) {
  $parcel                              = new Parcel();
  $parcel->reference                   = $data['reference_text'];
  $parcel->measurements                = new ParcelMeasurements();
  $parcel->measurements->weight        = new Measurement();
  $parcel->measurements->weight->value = intval($weight);
  $parcel->measurements->weight->unit  = 'g';
  $parcel->measurements->width         = new Measurement();
  $parcel->measurements->width->value  = 0;
  $parcel->measurements->width->unit   = 'cm';
  $parcel->measurements->height        = new Measurement();
  $parcel->measurements->height->value = 0;
  $parcel->measurements->height->unit  = 'cm';
  $parcel->measurements->depth         = new Measurement();
  $parcel->measurements->depth->value  = 0;
  $parcel->measurements->depth->unit   = 'cm';
  $parcel->contents                    = [];
  $details->parcels[]                  = $parcel;
}

$details->sender = $this->sender;

$details->recipient              = new Address();
$details->recipient->contactName = $data['name'];
$details->recipient->companyName = $data['company_name'];
$details->recipient->email       = $data['email'];
$details->recipient->phone       = $data['phone'];
$addressLine                     = $data['address'] . ' ' . $data['house_number'] . ($data['number_addon'] ? ' ' . $data[''] : '');
$details->recipient->addressLine = $addressLine;
$details->recipient->postal      = $data['zipcode'];
$details->recipient->city        = $data['city'];
$details->recipient->country     = $data['country'];

$details->featureCodes->deliverInMailBox       = false;
$details->featureCodes->maxDeliveryAttempts    = null;
$details->featureCodes->maxHoursOutsideFreezer = null;

$shipment = TrunkrsShipment::create($details);
```

**Comment by fean** [comment]
Hey @JSRM99!

Thanks for reporting your issue!
This seems to be a problem in our back-end. The back-end team has been notified!

I'll keep you updated on the progress of this issue! 🚀

**Comment by fean** [comment]
Hey @JSRM99!

We've released v2.0.2 of the Trunkrs SDK, it should take care of this issue. We're also fixing this in the back-end as well.
The back-end release has been scheduled for next week.

**Comment by stonjohnsson** [comment]
Hi @fean , when will the fix be applied on the server side of Trunkrs? Unfortunately we cant create shipments with this v2 API.

**Comment by fean** [comment]
Hey there @stonjohnsson! 

Due it being an exceptionally busy period, the back-end team has not been able to fix that yet. I have released a set of fixes and changes that should let you create shipments against our V2 api.

Could you please install version `2.1.0` of the SDK and try again.

Please let me know if you experience any more problems with our SDK or API.
