### ISSUE TITLE
ServerValidationException throws Exception

### ISSUE THREAD

**Issue by JSRM99** [Trunkrs/Trunkrs-SDK-PHP#26]
**Trunkrs SDK version(s) affected**: 2.0.0
**PHP version(s) affected**: 7.3.11

**Description**  
The ServerValidationException throws an Exception in the constructor when trying to read the "message" property from the JSON.

**How to reproduce**  
Create a for example a shipment that will make the server return a validation error.

**Possible Solution**  
By the looks of it the correct data to be read is in the "reason" property instead of the "message" one.
Possibly change it to that?

**Additional context**  
Location where exception gets thrown is marked in yellow:
![image](https://user-images.githubusercontent.com/37828702/107035828-024acf80-67b9-11eb-8efd-7d711b4b32e8.png)

**Comment by fean** [comment]
Thanks @JSRM99, very good catch! 👍
