### ISSUE TITLE
Usage of PHP 8 function when requirements specify PHP 7 or higher

### ISSUE THREAD

**Issue by JSRM99** [Trunkrs/Trunkrs-SDK-PHP#35]
**Trunkrs SDK version(s) affected**: 2.1.3
**PHP version(s) affected**: <8

**Description**  
The function `str_starts_with()` is used. This is a PHP >=8 function.
See: https://www.php.net/manual/en/function.str-starts-with.php

**How to reproduce**  
Try to use package whilst using a PHP version lower than 8.

**Possible Solution**  
Use `preg_match('/^http/i', $resource)` [here ](https://github.com/Trunkrs/Trunkrs-SDK-PHP/blob/9c54ee5fcf1df9ea4d6e3aea8a505eabc688d13c/lib/RequestHandler.php#L14) instead.
See: https://www.php.net/manual/en/function.preg-match.php

**Comment by fean** [comment]
Hey Juup!

I see! A new release is on its way! 🙂
