### ISSUE TITLE
"Undefined property: stdClass::$address" when trying to use Shipment::find($id)

### ISSUE THREAD

**Issue by JSRM99** [Trunkrs/Trunkrs-SDK-PHP#38]
**Trunkrs SDK version(s) affected**: 2.1.4
**PHP version(s) affected**: 7.3

**Description**  
When trying to retrieve a shipment using the static `find($trunkrsNr)` we encounter the following exception:
```
(ErrorException(code: 0): Undefined property: stdClass::$address at trunkrs/sdk/lib/Address.php:22)
[stacktrace] 
#0 trunkrs/sdk/lib/Address.php(22): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(8, 'Undefined prope...', '/home/forge/acc...', 22, Array)
#1 trunkrs/sdk/lib/Address.php(113): Trunkrs\\SDK\\Address::applyV2(Object(Trunkrs\\SDK\\Address), Object(stdClass)) 
#2 trunkrs/sdk/lib/Shipment.php(28): Trunkrs\\SDK\\Address->__construct(Object(stdClass)) 
#3 trunkrs/sdk/lib/Shipment.php(262): Trunkrs\\SDK\\Shipment::applyV2(Object(Trunkrs\\SDK\\Shipment), Object(stdClass))
#4 trunkrs/sdk/lib/Shipment.php(81): Trunkrs\\SDK\\Shipment->__construct(Object(stdClass)) 
```

**How to reproduce**  
Try to use the static `find()` function against the production API.
It seems that the acceptance API is working as intended.

**Additional context**  
The issue started occurring yesterday evening.
Yesterday morning, everything was still all fine. 
We did not have a release / code changes on our side between the time that it worked and the time that it stopped working.

**Comment by fean** [comment]
Hey @JSRM99!

Ah, something must have changed on our end! Sorry about that! I'll look into it with the back-end crew!
I'll have an answer or SDK update for you ASAP! 🙂
